**Import the Library**

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import klib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

**Read dataset**

In [11]:
df = pd.read_csv("housing.csv")


**analaysis the data**

In [12]:
df.head()

Crim    Zn  Indus  Chas    Nox     Rm   Age     Dis  Rad  Tax  PtRatio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  Lstat  Medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [13]:
df.describe()

Crim          Zn       Indus        Chas         Nox          Rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              Age         Dis         Rad         Tax     PtRatio           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            Lstat        Medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Crim     506 non-null    float64
 1   Zn       506 non-null    float64
 2   Indus    506 non-null    float64
 3   Chas     506 non-null    int64  
 4   Nox      506 non-null    float64
 5   Rm       506 non-null    float64
 6   Age      506 non-null    float64
 7   Dis      506 non-null    float64
 8   Rad      506 non-null    int64  
 9   Tax      506 non-null    int64  
 10  PtRatio  506 non-null    float64
 11  B        506 non-null    float64
 12  Lstat    506 non-null    float64
 13  Medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [15]:
print('jumlah baris :', df.shape[0])
print('jumlah kolom :', df.shape[1])

jumlah baris : 506
jumlah kolom : 14


In [16]:
list_item =[]
for col in df.columns:
    list_item.append([col,df[col].dtype, df[col].isna().sum(), 100*df[col].isna().sum()/len(df[col]),df[col].unique(), df[col].unique()[:4]])
desc_df = pd.DataFrame(data=list_item, columns='Feature Data_type Null_num Null_pct Unique_num Unique_sample'.split()) 
desc_df  

Feature Data_type  Null_num  Null_pct  \
0      Crim   float64         0       0.0   
1        Zn   float64         0       0.0   
2     Indus   float64         0       0.0   
3      Chas     int64         0       0.0   
4       Nox   float64         0       0.0   
5        Rm   float64         0       0.0   
6       Age   float64         0       0.0   
7       Dis   float64         0       0.0   
8       Rad     int64         0       0.0   
9       Tax     int64         0       0.0   
10  PtRatio   float64         0       0.0   
11        B   float64         0       0.0   
12    Lstat   float64         0       0.0   
13     Medv   float64         0       0.0   

                                           Unique_num  \
0   [0.00632, 0.02731, 0.02729, 0.03237, 0.06905, ...   
1   [18.0, 0.0, 12.5, 75.0, 21.0, 90.0, 85.0, 100....   
2   [2.31, 7.07, 2.18, 7.87, 8.14, 5.96, 2.95, 6.9...   
3                                              [0, 1]   
4   [0.538, 0.469, 0.458, 0.524, 0.499, 0.428, 0.4...   
5   [6.575, 6.421, 7.185, 6.998, 7.147, 6.43, 6.01...   
6   [65.2, 78.9, 61.1, 45.8, 54.2, 58.7, 66.6, 96....   
7   [4.09, 4.9671, 6.0622, 5.5605, 5.9505, 6.0821,...   
8                        [1, 2, 3, 5, 4, 8, 6, 7, 24]   
9   [296, 242, 222, 311, 307, 279, 252, 233, 243, ...   
10  [15.3, 17.8, 18.7, 15.2, 21.0, 19.2, 18.3, 17....   
11  [396.9, 392.83, 394.63, 394.12, 395.6, 386.63,...   
12  [4.98, 9.14, 4.03, 2.94, 5.33, 5.21, 12.43, 19...   
13  [24.0, 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27....   

                           Unique_sample  
0   [0.00632, 0.02731, 0.02729, 0.03237]  
1                [18.0, 0.0, 12.5, 75.0]  
2               [2.31, 7.07, 2.18, 7.87]  
3                                 [0, 1]  
4           [0.538, 0.469, 0.458, 0.524]  
5           [6.575, 6.421, 7.185, 6.998]  
6               [65.2, 78.9, 61.1, 45.8]  
7         [4.09, 4.9671, 6.0622, 5.5605]  
8                           [1, 2, 3, 5]  
9                   [296, 242, 222, 311]  
10              [15.3, 17.8, 18.7, 15.2]  
11       [396.9, 392.83, 394.63, 394.12]  
12              [4.98, 9.14, 4.03, 2.94]  
13              [24.0, 21.6, 34.7, 33.4]

**Split the data into dependent (Y) and independent (x) variable**

In [18]:
data = df.values
X, y = data[:, :-1], data[:, -1]
print(X.shape, y.shape)

(506, 13) (506,)


In [35]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [33]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

**Split data into train and test**

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [20]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(339, 13) (167, 13) (339,) (167,)


**Fit linear regression model to training Data**

In [23]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

**Predict the test data using liner regression model**

In [24]:
yhat = model.predict(X_test)

**evaluating using MAE*

In [25]:
mae = mean_absolute_error(y_test, yhat)
print('MAE: %.3f' % mae)

MAE: 3.417


In [36]:
yhat

array([32.10658829, 27.9386472 , 17.87780921, 21.13744566, 17.69499341,
       20.72894849, 32.25500102, 17.80071978, 21.8813407 , 26.45903146,
       26.52907372, 29.01743447, 20.52095683, 25.7910785 , 22.86400748,
       18.54838252, 16.93184765, 39.48741226, 29.44295087,  9.13200254,
       20.24363791, 15.9942691 , 25.25533216, 24.96241991, 30.65238513,
        8.7146305 , 13.6093357 , 16.63322355, 36.57984366, 13.54816254,
       21.33638228, 13.59496885, 43.61906846, 17.59554383, 21.3523854 ,
       20.63407678, 17.45339535, 27.69589782,  5.94147776, 19.283448  ,
       24.02130768, 21.56845054, 28.93178756, 15.71195872, 18.39358807,
       14.17332671, 37.62545365, 16.88047814, 24.95874377, 19.33143005,
       25.44168483, 24.11602471, 24.74276864, 26.14560591,  5.02095336,
       23.91862301, 10.66775087, 26.45358394, 16.87793246, 36.85981526,
       18.80895992, 27.30729563, 15.76086137, 17.3095321 , 11.73564422,
       32.15136007, 37.70503519, 21.9049063 , 24.43957894, 24.54

In [39]:
y_test

array([28.2, 23.9, 16.6, 22. , 20.8, 23. , 27.9, 14.5, 21.5, 22.6, 23.7,
       31.2, 19.3, 19.4, 19.4, 27.9, 13.9, 50. , 24.1, 14.6, 16.2, 15.6,
       23.8, 25. , 23.5,  8.3, 13.5, 17.5, 43.1, 11.5, 24.1, 18.5, 50. ,
       12.6, 19.8, 24.5, 14.9, 36.2, 11.9, 19.1, 22.6, 20.7, 30.1, 13.3,
       14.6,  8.4, 50. , 12.7, 25. , 18.6, 29.8, 22.2, 28.7, 23.8,  8.1,
       22.2,  6.3, 22.1, 17.5, 48.3, 16.7, 26.6,  8.5, 14.5, 23.7, 37.2,
       41.7, 16.5, 21.7, 22.7, 23. , 10.5, 21.9, 21. , 20.4, 21.8, 50. ,
       22. , 23.3, 37.3, 18. , 19.2, 34.9, 13.4, 22.9, 22.5, 13. , 24.6,
       18.3, 18.1, 23.9, 50. , 13.6, 22.9, 10.9, 18.9, 22.4, 22.9, 44.8,
       21.7, 10.2, 15.4, 25.3, 23.3,  7.2, 21.2, 11.7, 27. , 29.6, 26.5,
       43.5, 23.6, 11. , 33.4, 36. , 36.4, 19. , 20.2, 34.9, 50. , 19.3,
       14.9, 26.6, 19.9, 24.8, 21.2, 23.9, 20.6, 23.1, 28. , 20. , 23.1,
       25. ,  9.7, 23.9, 36.1, 13.4, 12.7, 39.8, 10.4, 20.6, 17.8, 19.5,
       23.7, 28.5, 24.3, 23.8, 19.1, 28.4, 20.5, 33

**Outlier Detection with Isolation Forest**

# identify outliers in the training dataset

In [27]:
from sklearn.ensemble import IsolationForest
from sklearn.metrics import mean_absolute_error

iso = IsolationForest(contamination=0.1)
yhat = iso.fit_predict(X_train)

# select all rows that are not outliers

In [28]:
mask = yhat != -1
X_train, y_train = X_train[mask, :], y_train[mask]

# summarize the shape of the updated training dataset

In [29]:
print(X_train.shape, y_train.shape)

(305, 13) (305,)


# fit the model

In [30]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

# evaluate the model

In [31]:
yhat = model.predict(X_test)

# evaluate predictions

In [32]:
mae = mean_absolute_error(y_test, yhat)
print('MAE: %.3f' % mae)

MAE: 3.202


In [40]:
yhat

array([32.10658829, 27.9386472 , 17.87780921, 21.13744566, 17.69499341,
       20.72894849, 32.25500102, 17.80071978, 21.8813407 , 26.45903146,
       26.52907372, 29.01743447, 20.52095683, 25.7910785 , 22.86400748,
       18.54838252, 16.93184765, 39.48741226, 29.44295087,  9.13200254,
       20.24363791, 15.9942691 , 25.25533216, 24.96241991, 30.65238513,
        8.7146305 , 13.6093357 , 16.63322355, 36.57984366, 13.54816254,
       21.33638228, 13.59496885, 43.61906846, 17.59554383, 21.3523854 ,
       20.63407678, 17.45339535, 27.69589782,  5.94147776, 19.283448  ,
       24.02130768, 21.56845054, 28.93178756, 15.71195872, 18.39358807,
       14.17332671, 37.62545365, 16.88047814, 24.95874377, 19.33143005,
       25.44168483, 24.11602471, 24.74276864, 26.14560591,  5.02095336,
       23.91862301, 10.66775087, 26.45358394, 16.87793246, 36.85981526,
       18.80895992, 27.30729563, 15.76086137, 17.3095321 , 11.73564422,
       32.15136007, 37.70503519, 21.9049063 , 24.43957894, 24.54

In [41]:
y_test

array([28.2, 23.9, 16.6, 22. , 20.8, 23. , 27.9, 14.5, 21.5, 22.6, 23.7,
       31.2, 19.3, 19.4, 19.4, 27.9, 13.9, 50. , 24.1, 14.6, 16.2, 15.6,
       23.8, 25. , 23.5,  8.3, 13.5, 17.5, 43.1, 11.5, 24.1, 18.5, 50. ,
       12.6, 19.8, 24.5, 14.9, 36.2, 11.9, 19.1, 22.6, 20.7, 30.1, 13.3,
       14.6,  8.4, 50. , 12.7, 25. , 18.6, 29.8, 22.2, 28.7, 23.8,  8.1,
       22.2,  6.3, 22.1, 17.5, 48.3, 16.7, 26.6,  8.5, 14.5, 23.7, 37.2,
       41.7, 16.5, 21.7, 22.7, 23. , 10.5, 21.9, 21. , 20.4, 21.8, 50. ,
       22. , 23.3, 37.3, 18. , 19.2, 34.9, 13.4, 22.9, 22.5, 13. , 24.6,
       18.3, 18.1, 23.9, 50. , 13.6, 22.9, 10.9, 18.9, 22.4, 22.9, 44.8,
       21.7, 10.2, 15.4, 25.3, 23.3,  7.2, 21.2, 11.7, 27. , 29.6, 26.5,
       43.5, 23.6, 11. , 33.4, 36. , 36.4, 19. , 20.2, 34.9, 50. , 19.3,
       14.9, 26.6, 19.9, 24.8, 21.2, 23.9, 20.6, 23.1, 28. , 20. , 23.1,
       25. ,  9.7, 23.9, 36.1, 13.4, 12.7, 39.8, 10.4, 20.6, 17.8, 19.5,
       23.7, 28.5, 24.3, 23.8, 19.1, 28.4, 20.5, 33