In [46]:
#import library pandas
import pandas as pd

dataset=pd.read_csv('telecustomer.csv')

In [16]:
dataset

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies  \
0                  No          No          No              No   
1                 Yes          No          No              No   
2                  No          No          No              No   
3                 Yes         Yes          No              No   
4                  No          No          No              No   
...               ...         ...         ...             ...   
7038              Yes         Yes         Yes             Yes   
7039              Yes          No         Yes             Yes   
7040               No          No          No              No   
7041               No          No          No              No   
7042              Yes         Yes         Yes             Yes   

     PaperlessBilling  MonthlyCharges TotalCharges Churn  
0                 Yes           29.85        29.85    No  
1                  No           56.95       1889.5    No  
2                 Yes           53.85       108.15   Yes  
3                  No           42.30      1840.75    No  
4                 Yes           70.70       151.65   Yes  
...               ...             ...          ...   ...  
7038              Yes           84.80       1990.5    No  
7039              Yes          103.20       7362.9    No  
7040              Yes           29.60       346.45    No  
7041              Yes           74.40        306.6   Yes  
7042              Yes          105.65       6844.5    No  

[7043 rows x 18 columns]

In [47]:
dataset.shape

(7043, 11)

In [48]:
dataset.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'InternetService', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'Churn'],
      dtype='object')

In [49]:
dataset.isnull().sum()


gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
InternetService     0
PaperlessBilling    0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [62]:
X=dataset.iloc[:,[1,2,3,4,5,6,7,8,9]].values
Y=dataset.iloc[:,10].values

In [63]:
X

array([[0, 'Yes', 'No', ..., 'Yes', 29.85, '29.85'],
       [0, 'No', 'No', ..., 'No', 56.95, '1889.5'],
       [0, 'No', 'No', ..., 'Yes', 53.85, '108.15'],
       ...,
       [0, 'Yes', 'Yes', ..., 'Yes', 29.6, '346.45'],
       [1, 'Yes', 'No', ..., 'Yes', 74.4, '306.6'],
       [0, 'No', 'No', ..., 'Yes', 105.65, '6844.5']], dtype=object)

In [64]:
Y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [82]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(X).toarray())
# merge with main df bridge_df on key values
X = X.join(enc)
X


AttributeError: 'numpy.ndarray' object has no attribute 'join'

In [80]:
X.shape

(7043, 12)

In [78]:
X

array([[0.0, 1.0, 0.0, ..., 'Yes', 29.85, '29.85'],
       [0.0, 1.0, 0.0, ..., 'No', 56.95, '1889.5'],
       [0.0, 1.0, 0.0, ..., 'Yes', 53.85, '108.15'],
       ...,
       [0.0, 1.0, 0.0, ..., 'Yes', 29.6, '346.45'],
       [1.0, 0.0, 1.0, ..., 'Yes', 74.4, '306.6'],
       [0.0, 1.0, 0.0, ..., 'Yes', 105.65, '6844.5']], dtype=object)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [68]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

Y = labelencoder.fit_transform(Y)

In [69]:
X

array([[1.0, 0.0, 'Yes', ..., 'Yes', 29.85, '29.85'],
       [1.0, 0.0, 'No', ..., 'No', 56.95, '1889.5'],
       [1.0, 0.0, 'No', ..., 'Yes', 53.85, '108.15'],
       ...,
       [1.0, 0.0, 'Yes', ..., 'Yes', 29.6, '346.45'],
       [0.0, 1.0, 'Yes', ..., 'Yes', 74.4, '306.6'],
       [1.0, 0.0, 'No', ..., 'Yes', 105.65, '6844.5']], dtype=object)

In [70]:
Y

array([0, 0, 1, ..., 0, 1, 0])

In [71]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import matplotlib.ticker as ticker
%matplotlib inline

In [72]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)

ValueError: could not convert string to float: 'Yes'

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
#Train Model and Predict
k = 4  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
Pred_y = neigh.predict(X_test)
print("Accuracy of model at K=4 is",metrics.accuracy_score(y_test, Pred_y))

In [40]:
Y

array([0, 0, 1, ..., 0, 1, 0])