## Load Data

In [2]:
# Import Package
import numpy as np
import pandas as pd

In [3]:
# Load dataset
df = pd.read_csv('dataset.csv')

In [4]:
df

sepal.length  sepal.width  petal.length  petal.width    variety  label
0             5.1          3.5           1.4          0.2     Setosa      0
1             4.9          3.0           1.4          0.2     Setosa      0
2             4.7          3.2           1.3          0.2     Setosa      0
3             4.6          3.1           1.5          0.2     Setosa      0
4             5.0          3.6           1.4          0.2     Setosa      0
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  Virginica      2
146           6.3          2.5           5.0          1.9  Virginica      2
147           6.5          3.0           5.2          2.0  Virginica      2
148           6.2          3.4           5.4          2.3  Virginica      2
149           5.9          3.0           5.1          1.8  Virginica      2

[150 rows x 6 columns]

In [5]:
# Cek tipedata df
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
label             int64
dtype: object

In [6]:
# Akses kolom df
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [7]:
# Akses kolom sepal.length
df['sepal.length'].values

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [8]:
# Akses hanya nilai semua kolom
feature = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values

In [9]:
# Akses label
label = df['label'].values

In [10]:
# Ubah ke numpy array
x = np.array(feature)
y = np.array(label)

In [11]:
x.shape

(150, 4)

In [12]:
y.shape

(150,)

## Training Model

In [13]:
from sklearn.preprocessing import StandardScaler

$$\frac{x-mean}{std}$$

In [14]:
# Mencari rata-rata per kolom / per atribut
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
atribut_mean = x.mean(axis=0)

In [16]:
atribut_std = x.std(axis=0)

## Normalisasi

In [17]:
x_norm = StandardScaler().fit_transform(x)

In [18]:
x_norm.shape

(150, 4)

In [19]:
x_norm

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

## Training
### Train test split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25, stratify=y, random_state=12)

In [22]:
x_train.shape

(112, 4)

In [23]:
x_test.shape

(38, 4)

In [24]:
y_train.shape

(112,)

## Training neural network

In [25]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [26]:
# Membuat blueprint model
model = Sequential()

# Tentukan layer per model
model.add(Dense(64, input_dim=4, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Tentukan loss, algoritma belajar, dan jenis evaluasi
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
# Isi data ke neural network dan train
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 81ms/step - loss: 0.9453 - accuracy: 0.6786 - val_loss: 0.9148 - val_accuracy: 0.6579
Epoch 2/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8533 - accuracy: 0.8036 - val_loss: 0.8435 - val_accuracy: 0.7105
Epoch 3/100
4/4 [==============================] - 0s 8ms/step - loss: 0.7780 - accuracy: 0.8393 - val_loss: 0.7852 - val_accuracy: 0.7105
Epoch 4/100
4/4 [==============================] - 0s 8ms/step - loss: 0.7147 - accuracy: 0.8482 - val_loss: 0.7370 - val_accuracy: 0.7105
Epoch 5/100
4/4 [==============================] - 0s 7ms/step - loss: 0.6580 - accuracy: 0.8393 - val_loss: 0.6951 - val_accuracy: 0.7105
Epoch 6/100
4/4 [==============================] - 0s 8ms/step - loss: 0.6074 - accuracy: 0.8393 - val_loss: 0.6577 - val_accuracy: 0.7105
Epoch 7/100
4/4 [==============================] - 0s 8ms/step - loss: 0.5620 - accuracy: 0.8482 - val_loss: 0.6262 - val_accuracy: 0.7368
Epoch 8/100
4/4 [=========

### Save model

In [28]:
model.save('model.h5')

### Load model

In [29]:
from tensorflow.keras.models import load_model

In [30]:
model = load_model('model.h5')

----------------

### Predictions

#### Prepare data

In [31]:
# Menggunakan data dari df
df.iloc[100, :]

sepal.length          6.3
sepal.width           3.3
petal.length          6.0
petal.width           2.5
variety         Virginica
label                   2
Name: 100, dtype: object

In [32]:
new_data = [[6.3, 3.3, 6, 2.5]]

In [33]:
x_pred = np.array(new_data)

In [34]:
x_pred

array([[6.3, 3.3, 6. , 2.5]])

### Normalisasi

In [35]:
atribut_mean

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [36]:
atribut_std

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [37]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [38]:
df.iloc[100, :]

sepal.length          6.3
sepal.width           3.3
petal.length          6.0
petal.width           2.5
variety         Virginica
label                   2
Name: 100, dtype: object

$$\frac{x-mean}{std}$$

In [39]:
sepalLength = (6.3 - atribut_mean[0]) / atribut_std[0]
sepalWidth = (3.3 - atribut_mean[1]) / atribut_std[1]
petalLength = (6 - atribut_mean[2]) / atribut_std[2]
petalWidth = (2.5 - atribut_mean[3]) / atribut_std[3]

In [40]:
xPred = np.array([[sepalLength, sepalWidth, petalLength, petalWidth]])

### Prediction

In [41]:
hasil = model.predict(xPred)

In [42]:
hasil

array([[3.3059023e-05, 1.1300693e-04, 9.9985397e-01]], dtype=float32)

In [43]:
np.argmax(hasil, axis=1)

array([2], dtype=int64)